29 mandatory studen4 r02 d02
davidg43/Acme-SF-D pull request #47
Opened 2024-03-01 15:40 UTC by Naredo

2024-03-04 10:00 UTC, davidg43 requested changes

2024-03-04 10:00 UTC, davidg43 commented on src/main/webapp/WEB-INF/resources/sample-data/sponsor.csv
try to use a negative test to be sure about money assert.

2024-03-05 08:16 UTC, Naredo commented
Problems fixeds

2024-03-05 17:19 UTC, davidg43 requested changes

2024-03-05 17:19 UTC, davidg43 commented on njgsfs
You cant commit this file

2024-03-05 17:19 UTC, davidg43 commented on .settings/org.eclipse.wst.common.component
Its important to resolve this unexpected differences!

2024-03-08 12:06 UTC, merged